node {
  stage 'buildIndev'
  openshiftBuild(namespace: 'dev', buildConfig: 'welcome', showBuildLogs: 'true')
  
  stage 'deployIndev'
  openshiftDeploy(namespace: 'dev', deploymentConfig: 'welcome')
  openshiftScale(namespace: 'dev', deploymentConfig: 'welcome',replicaCount: '2')
  openshiftTag(namespace: 'dev', sourceStream: 'welcome',  sourceTag: 'latest', destinationStream: 'welcome', destinationTag: 'promoteToQA', destinationNamespace: 'qa')

  stage 'deployInQA'
  openshiftDeploy(namespace: 'qa', deploymentConfig: 'welcome')
  openshiftScale(namespace: 'qa', deploymentConfig: 'welcome',replicaCount: '3')
}
