apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: denyreviewsv3
spec:
  match: destination.labels["app"] == "ratings" && source.labels["app"]=="reviews" && source.labels["version"] == "v3"
  actions:
  - handler: denyall.denier
    instances:
    - denyrequest.checknothing

